apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
spec:
  limits:
  - default: # this section defines default limits
      cpu: 500m
      memory: 512Mi
    defaultRequest: # this section defines default requests
      cpu: 100m
      memory: 128Mi
    max: # max define the limit range
      cpu: "1"
      memory: "1Gi"
    type: Container

