apiVersion: v1
kind: Pod
metadata:
  name: test-staging-pod
  namespace: staging
spec:
  containers:
    - name: big-container
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      resources:
        requests:
          cpu: "1"
          memory: 1Gi   
        limits:
          cpu: "1"
          memory: 1Gi
