apiVersion: v1
kind: Service
metadata:
  labels:
    app: exam3-app
  name: public-exam3-service
spec:
  ports:
    - name: 80-9000
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: exam3-app
  type: LoadBalancer
status:
  loadBalancer: {}

