apiVersion: v1
kind: Service
metadata:
  labels:
    env: blue
  name: blue-test-service
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
    role: blue
  type: LoadBalancer
status:
  loadBalancer: {}

