apiVersion: v1
kind: Service
metadata:
  labels:
    env: green
  name: green-test-service
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
    role: green
  type: LoadBalancer
status:
  loadBalancer: {}

