apiVersion: v1
kind: Pod
metadata:
  name: app-pod
  labels:
    app: app
spec:
  containers:
    - name: app
      image: service:1.2
      imagePullPolicy: Never
      ports:
        - containerPort: 3000

