apiVersion: v1
kind: Service
metadata:
  name: svc-safc
spec:
  ports:
  - name: 9001-8080
    nodePort: 31111
    port: 9001
    protocol: TCP
    targetPort: 80
  selector:
    app: tickets
    club: safc
  type: NodePort

