apiVersion: v1
kind: Service
metadata:
  name: blue-test-service
  labels:
    env: blue
spec:
  selector:
    app: nginx
    role: blue
  ports:
    - port: 9000
      targetPort: 80
  type: LoadBalancer


