apiVersion: v1
kind: Service
metadata:
  name: green-test-service
  labels:
    env: green
spec:
  selector:
    app: nginx
    role: green
  ports:
    - port: 9001
      targetPort: 80
  type: LoadBalancer


