apiVersion: v1
kind: Service
metadata:
  name: public-service
  labels:
    env: prod
spec:
  selector:
    app: nginx
    role: blue
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer

