apiVersion: v1
kind: Service
metadata:
  labels:
    env: prod
  name: public-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
    role: blue
  type: LoadBalancer
status:
  loadBalancer: {}

