apiVersion: v1
kind: Pod
metadata:
  name: memory-app
spec:
  containers:
  - name: stress
    image: polinux/stress
    command: ["stress"]
    args: ["--vm","1","--vm-bytes","300M","--vm-hang","1"]
    resources:
      requests:
        cpu: "15m"
        memory: "200Mi"
      limits:
        cpu: "30m"
        memory: "350Mi"
