apiVersion: batch/v1
kind: CronJob
metadata:
  name: cleaner
spec:
  schedule: "*/1 * * * *" #every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cleaner
            image: docker.io/busybox:1.37
            imagePullPolicy: IfNotPresent
            command: ["/bin/sh", "-c"]
            args: ["echo Cleaning temp files at $(date)."]
          restartPolicy: OnFailure

