apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: log-writer
spec:
  selector:
    matchLabels:
      name: log-writer
  template:
    metadata:
      labels:
        name: log-writer
    spec:
      containers:
      - name: logger
        image: docker.io/busybox:1.37
        command: ["/bin/sh"]
        imagePullPolicy: IfNotPresent
        args: ["-c","while true; do echo $(date) Writing logs...; sleep 30; done"]

