apiVersion: v1
kind: Pod
metadata:
  name: slow-start
spec:
  containers:
  - name: busybox-slow-start
    image: busybox
    ports:
    - containerPort: 9090
    args:
    - /bin/sh
    - -c
    - |
      while true; do echo "hello" | nc -l -p 9090; done &
      sleep 30
      touch /tmp/live
      tail -f /dev/null
    startupProbe:
      exec:
        command:
          - cat
          - /tmp/live1
      initialDelaySeconds: 30
      failureThreshold: 5
    readinessProbe:
      tcpSocket:
        port: 9090
      successThreshold: 2
    livenessProbe:
      tcpSocket:
        port: 9090
      initialDelaySeconds: 10
      periodSeconds: 30


